repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml

  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        entry: npx prettier --write
        language: system
        files: \.(js|jsx|ts|tsx|css|scss|html|json|md|yaml|yml)$

      - id: typescript-check
        name: TypeScript type check
        entry: npm run type-check
        language: system
        files: \.(ts|tsx)$
        pass_filenames: false
