import type { Base24Colors, FlavorKey, ThemeParams, AccentColorKey } from '../types/index.ts';
import { Base24 } from '../classes/Base24.ts';

export const createNvimTheme = (
  colors: Base24Colors,
  themeName: string,
  flavor: FlavorKey
): string => `-- ${themeName} (${flavor} flavor)
-- Generated by Lumina Theme Generator

local colors = {
${Object.entries(colors)
  .map(([key, value]) => `  ${key} = "${value}",`)
  .join('\n')}
}

local theme = {
  Normal = { fg = colors.base05, bg = colors.base00 },
  NormalFloat = { fg = colors.base05, bg = colors.base01 },
  Comment = { fg = colors.base03, italic = true },

  Constant = { fg = colors.base09 },
  String = { fg = colors.base0B },
  Character = { fg = colors.base0B },
  Number = { fg = colors.base09 },
  Boolean = { fg = colors.base09 },
  Float = { fg = colors.base09 },

  Identifier = { fg = colors.base08 },
  Function = { fg = colors.base0D },

  Statement = { fg = colors.base0E },
  Conditional = { fg = colors.base0E },
  Repeat = { fg = colors.base0E },
  Label = { fg = colors.base0A },
  Operator = { fg = colors.base05 },
  Keyword = { fg = colors.base0E, bold = true },
  Exception = { fg = colors.base08 },

  Type = { fg = colors.base0A },
  StorageClass = { fg = colors.base0A },
  Structure = { fg = colors.base0E },

  Special = { fg = colors.base0C },
  SpecialChar = { fg = colors.base0F },
  Tag = { fg = colors.base0A },
  Delimiter = { fg = colors.base0F },

  CursorLine = { bg = colors.base01 },
  Visual = { bg = colors.base02 },
  Search = { fg = colors.base00, bg = colors.base0A },
  LineNr = { fg = colors.base03 },
  StatusLine = { fg = colors.base04, bg = colors.base02 },

  ErrorMsg = { fg = colors.base08 },
  WarningMsg = { fg = colors.base09 },
  MoreMsg = { fg = colors.base0B },

  DiffAdd = { fg = colors.base0B, bg = colors.base00 },
  DiffChange = { fg = colors.base0A, bg = colors.base00 },
  DiffDelete = { fg = colors.base08, bg = colors.base00 },
  DiffText = { fg = colors.base0D, bg = colors.base00 },
}

for group, opts in pairs(theme) do
  vim.api.nvim_set_hl(0, group, opts)
end

return colors`;

export const createBase24Json = (colors: Base24Colors, themeName: string): string =>
  Base24.createBase24Json(colors, themeName);

export const createStylixTheme = (
  colors: Base24Colors,
  themeName: string,
  flavor: FlavorKey
): string => {
  const nixThemeName = themeName.toLowerCase().replace(/[^a-z0-9]/g, '-');
  const isLight = colors.base00 > colors.base05;

  return `# ${themeName} (${flavor} flavor) - Stylix Theme
# Generated by Lumina Theme Generator

{
  stylix = {
    enable = true;

    base16Scheme = {
${Object.entries(colors)
  .map(([key, value]) => `      ${key} = "${value.slice(1)}"; # ${Base24.getColorDescription(key)}`)
  .join('\n')}

      scheme = "${nixThemeName}";
      author = "Lumina Theme Generator";
    };

    polarity = "${isLight ? 'light' : 'dark'}";

    targets = {
      alacritty.enable = true;
      kitty.enable = true;
      neovim.enable = true;
      firefox.enable = true;
    };
  };
}`;
};

const getFinalHueForColor = (
  params: ThemeParams,
  colorKey: AccentColorKey,
  standardOffsets: number[] = Base24.STANDARD_OFFSETS
): number => {
  const baseHue = params.accentHue || 0;
  const colorIndex = Base24.getAccentColorIndex(colorKey);
  const standardOffset = standardOffsets[colorIndex] || 0;
  const customOffset = params.colorAdjustments?.[colorKey]?.hueOffset ?? 0;

  let finalHue = baseHue + standardOffset + customOffset;
  while (finalHue < 0) finalHue += 360;
  while (finalHue >= 360) finalHue -= 360;

  return Math.round(finalHue);
};

export const createThemeJson = (
  params: ThemeParams,
  themeName: string,
  themeTagline: string,
  themeInspirations: string,
  currentFlavor: FlavorKey
): string => {
  const accentColors = {
    red: { hue: getFinalHueForColor(params, 'base08') },
    orange: { hue: getFinalHueForColor(params, 'base09') },
    yellow: { hue: getFinalHueForColor(params, 'base0A') },
    green: { hue: getFinalHueForColor(params, 'base0B') },
    cyan: { hue: getFinalHueForColor(params, 'base0C') },
    blue: { hue: getFinalHueForColor(params, 'base0D') },
    purple: { hue: getFinalHueForColor(params, 'base0E') },
    pink: { hue: getFinalHueForColor(params, 'base0F') },
  };

  const flavors = {
    muted: {
      accentHue: currentFlavor === 'muted' ? params.accentHue : 0,
      accentSat: currentFlavor === 'muted' ? params.accentSat : 50,
      accentLight: currentFlavor === 'muted' ? params.accentLight : 65,
      commentLight: currentFlavor === 'muted' ? params.commentLight : 45,
    },
    balanced: {
      accentHue: currentFlavor === 'balanced' ? params.accentHue : 0,
      accentSat: currentFlavor === 'balanced' ? params.accentSat : 70,
      accentLight: currentFlavor === 'balanced' ? params.accentLight : 60,
      commentLight: currentFlavor === 'balanced' ? params.commentLight : 40,
    },
    bold: {
      accentHue: currentFlavor === 'bold' ? params.accentHue : 0,
      accentSat: currentFlavor === 'bold' ? params.accentSat : 85,
      accentLight: currentFlavor === 'bold' ? params.accentLight : 55,
      commentLight: currentFlavor === 'bold' ? params.commentLight : 35,
    },
  };

  const themeDefinition = {
    name: themeName,
    tagline: themeTagline,
    inspirations: themeInspirations,
    bgHue: params.bgHue,
    bgSat: params.bgSat,
    bgLight: params.bgLight,
    accentOffsets: accentColors,
    flavors,
  };

  return JSON.stringify(themeDefinition, null, 2);
};
